### ISSUE TITLE
Script works from main.py but not online

### ISSUE THREAD

**Issue by lvancraen** [lexpar/CTeam#15]
I've been having issues running scripts on my local server. Whereas, my script functions properly when I run it through main.py by changing the testscript, it doesn't seem to pass the syntax-Checker online. I've wrote it exactly the same. I'm running them both through the master branch. I've also pushed the code onto there, so if anyone wants to test it on there end, please do. Here is the script: 

if MY_ENERGY > 0 then
do
    attack();
done
endif

I receive this error: "Line: 4 Function Error: 'attack' is not compatible with arguments ()"

To run it on main.py, you need to create a second actor for this action to work.

Here's my main.py file:

from gamelogic.actor import Actor
from gamelogic.game_instance import GameInstance
import IPython

"""Use this file to set up tests and toy situations.
By running on command line, it will execute these lines then
open an IPython shell for you to interact with."""

testscript = """
if MY_ENERGY > 0 then
do
    attack();
done
endif
"""
testscript1 = """
if MY_ENERGY > 0 then
do
	sleep();
done
endif
"""

a = Actor(1, 1, "Alex", testscript)
b = Actor(1, 2, "Bob", testscript1)
g = GameInstance()
a.sleep = 10
#g.init_empty_world()
g.add_actor(a)
g.add_actor(b)
print(a.behaviours.rules[0].condition.eval(a))
IPython.embed()

**Comment by lexpar** [comment]
It depends how you wrote the `attack` function. The error you're getting is basically a catch all for some error in the function. You should put in some breakpoints and check where its getting cooked.

**Comment by lexpar** [comment]
If I had to guess, it would be because the `attack` function is assuming that there is a nearby actor to attack. The validator does not provide such a situation. It simply tries to run each script in an empty world with a single actor in it. It's likely that this is causing the bug.

**Comment by lvancraen** [comment]
Thanks! Fixed the bug
